### ISSUE TITLE
Error when turning on the server

### ISSUE THREAD

**Issue by shoucandanghehe** [MilSpecSG/MSDataSync#5]
[22:15:28] [pool-3-thread-2/ERROR] [Sponge]: The Scheduler tried to run the task msdatasync-A-19 owned by Plugin{id=msdatasync, name=MSDataSync, version=1.0.0-BETA1, description=A plugin to synchronize player inventories with a database, url=https://github.com/MilSpecSG/MSDataSync, authors=[Cableguy20], source=./mods/MSDataSync-Sponge-1.0.0-BETA1.jar}, but an error occured.
java.lang.IllegalStateException: MSRepository: DataStoreName has not been loaded yet!
        at rocks.milspecsg.msrepository.service.common.manager.CommonManager.getPrimaryComponent(CommonManager.java:117) ~[CommonManager.class:?]
        at rocks.milspecsg.msdatasync.service.sponge.tasks.SpongeSerializationTaskService.lambda$getSerializationTask$0(SpongeSerializationTaskService.java:64) ~[SpongeSerializationTaskService.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.9]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.1.9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_242]
        at rocks.milspecsg.msrepository.service.common.manager.CommonManager.getPrimaryComponent(CommonManager.java:113) ~[CommonManager.class:?]
        ... 8 more

I do n’t know Java, so I do n’t know what went wrong

**Comment by alexstaeding** [comment]
This will be fixed in the next version, 1.0.0-BETA2. In the meantime, can you try running `/sync reload` and putting the output here?

**Comment by shoucandanghehe** [comment]
> This will be fixed in the next version, 1.0.0-BETA2. In the meantime, can you try running `/sync reload` and putting the output here?
  
The log output is a bit too much, I put it in the attachment
[log.txt](https://github.com/AnvilPowered/DataSync/files/4295754/log.txt)
Sorry, I think we have a time difference，failed to reply in time

**Comment by alexstaeding** [comment]
From that log, it seems to be working properly. Are there any more errors? During serialization for example?

**Comment by shoucandanghehe** [comment]
I can restart the server and send you all the debugs
Please wait for me a few minutes

**Comment by shoucandanghehe** [comment]
[log.zip](https://github.com/AnvilPowered/DataSync/files/4296846/log.zip)
This is all the logs that start the server

**Comment by alexstaeding** [comment]
This should be fixed in latest version. Please update to [v0.7.0](https://ore.spongepowered.org/AnvilPowered/DataSync/versions/0.7.0) and try again. Note that this version requires Anvil [v0.2.0](https://ore.spongepowered.org/AnvilPowered/Anvil/versions/0.2.0). Make sure you rename your old data directory because the new data format is not compatible with the old one.
